name: Update DNS

on:
  push:
    branches:
    - dev

jobs:
  make_doc:
    name: Update DNS
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Update DNS
      run: poetry run python -m dns.sync
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
